changelog:
  categories:
    - title: "🚀 Features"
      labels: [enhancement]
    - title: "🐛 Bug Fixes"
      labels: [bug]
    - title: "🔄 Sync"
      labels: [sync]
    - title: "📖 Documentation"
      labels: [documentation]
    - title: "🔧 Maintenance"
      labels: [chore, dependencies]
  exclude:
    labels: [skip-changelog]
